### ISSUE TITLE
Log Error: Update for climate.gmg12135713 fails

### ISSUE THREAD

**Issue by Haloooch** [jwhitby91/gmg_home_assistant#2]
I've installed the custom component, and all appears to be working, however I'm seeing the following in the HA logs. Not sure if it's just log spam or indicating there is an underlying issue. It's being added to the logs :

`2022-05-08 18:13:31 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.gmg12135713_probe_2 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gmg/climate.py", line 271, in update
    self._state = self._grill.status()
  File "/config/custom_components/gmg/gmg.py", line 149, in status
    return self.gmg_status_response(list(self.send(grill.CODE_STATUS)))
TypeError: 'NoneType' object is not iterable
2022-05-08 18:16:30 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.gmg12135713 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gmg/climate.py", line 168, in update
    self._state = self._grill.status()
  File "/config/custom_components/gmg/gmg.py", line 149, in status
    return self.gmg_status_response(list(self.send(grill.CODE_STATUS)))
TypeError: 'NoneType' object is not iterable`

**Comment by jwhitby91** [comment]
Thanks for reporting this. I had seen this myself but hadn't had a chance to get around to looking at it.

It looks like sometimes the grill does not reply for the status (possible dropped packet I have to look into that more) and I had poor error handling for that. 

I just made a change in dev branch and on my HA instance. I won't push it to main yet until I test it out a bit more. Below is the commit for reference

[https://github.com/jwhitby91/gmg_home_assistant/commit/c8c30400ed73ca51d2806fadb2a68e17266e627a](url)

**Comment by jwhitby91** [comment]
I made a few changes earlier today and haven't seen any errors since

In HACS if you selected "show beta versions" when you added the repo you will be able to install the beta release. If not I'll push it to main release in day or two if nothing shows in logs again and you will get update too 

https://github.com/jwhitby91/gmg_home_assistant/releases/tag/v1.0.1-beta

**Comment by jwhitby91** [comment]
@Haloooch sorry for delay was caught up with work. 

The changes have been working well for me so I pushed new release and you should be able to update it in HACS now. 

Please let me know if you still spot any errors. I will close this for now as resolved

https://github.com/jwhitby91/gmg_home_assistant/releases/tag/v1.0.2

**Comment by Haloooch** [comment]
Just wanted to confirm I've been running the new release for a few days now. The 'object is not iterable' error has gone, error log is clean! Thx.
